using Amazon.S3;
using Amazon.S3.Model;
using Spikylin.Core;
using Spikylin.Features.Gallery.Dto;
using System.Text.Json;

namespace Spikylin.Features.Gallery;

public interface IThumbnailService
{
    public Task<IReadOnlyList<PhotoThumbnail>> GetThumbnailsAsync(CancellationToken cancellationToken = default);
}
public record PhotoThumbnail(string Key, Uri Url, PhotoMetadata PhotoMetadata);

public class ThumbnailService(
    S3Clients s3Clients,
    IConfiguration configuration) : IThumbnailService
{
    private readonly S3Options options = configuration.GetSection("S3").Get<S3Options>() ?? new();
    public async Task<IReadOnlyList<PhotoThumbnail>> GetThumbnailsAsync(CancellationToken cancellationToken = default)
    {
        try
        {
            using var response = await s3Clients.SpikylinS3.GetObjectAsync(new GetObjectRequest
            {
                BucketName = options.SpikylinS3Bucket.BucketName,
                Key = "manifest.json"
            }, cancellationToken).ConfigureAwait(false);

            var thumbnails = await JsonSerializer.DeserializeAsync<List<PhotoThumbnail>>(
                response.ResponseStream, cancellationToken: cancellationToken).ConfigureAwait(false);
            return thumbnails!
                    .OrderByDescending(thumbnail => thumbnail.PhotoMetadata.DateTime)
                    .ThenBy(thumbnail => thumbnail.Key, StringComparer.OrdinalIgnoreCase)
                    .ToArray();
        }
        catch (AmazonS3Exception ex) when (ex.StatusCode == System.Net.HttpStatusCode.NotFound)
        {
            // If manifest hasn't been generated by the worker yet, return empty list
            return Array.Empty<PhotoThumbnail>();
        }
    }
}