
services:
  spikylin:
    image: ghcr.io/clock1998/spikylin:${TAG}
    networks:
      - cloudflared-network-spikylin
    ports:
      - 80:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=80
    container_name: spikylin
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    container_name: cloudflared-tunnel-spikylin
    restart: always
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_SPIKYLIN_TOKEN}
    networks:
      - cloudflared-network-spikylin

networks:
  cloudflared-network-spikylin:
    driver: bridge
    name: cloudflared-network-spikylin
# docker compose -p services up -d
