name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@v4
    
    - name: Stop docker container
      run: docker compose -f ./Spikylin/docker-compose.yml down 
      
    - name: Build the Docker image
      run: docker compose build
